### ISSUE TITLE
Decide what technology to use

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/cdphe-accessible-covid19#1]
What framework has built in accessibility features for data visualizations? Let's decide on one to move forward.

**Comment by anotherpatrickcollins** [comment]
Heard good things from a friend about the React datavis library **Semiotic.**

**Comment by DC3PO** [comment]
Semiotic looks like it would be a good fit!  I used Material-UI for the covid app I built but I am open to anything.
