### ISSUE TITLE
Add sorting to incoming data so it can always grab the latest sets by by both 1 day offset, and 1 week offset

### ISSUE THREAD

**Issue by jberns** [codefordenver/cdphe-accessible-covid19#12]
Looking at the home page component, there is a today and yesterday value to calculate the deltas.  The data must be ordered correctly so it can be selected by a day offset to do daily and weekly calculations.

**Comment by galbwe** [comment]
@jberns I opened a [PR](https://github.com/codefordenver/cdphe-accessible-covid19/pull/16) for this

**Comment by jberns** [comment]
@galbwe Looks good!  Just merged it!
