### ISSUE TITLE
Create about page

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/cdphe-accessible-covid19#38]
As per @joel-oe-lacey and I's discussion on 4/19:

Let's create a small about page that discusses the project, why it was built, what it's for, who we are, etc.

Content: 
Code for Denver is a group of volunteer technologists who build software to help nonprofits and local government better serve their community.

This dashboard was built in response to the Colorado Department of Public Health and Environment's COVID-19 dashboard (link: https://covid19.colorado.gov/data) that we at Code for Denver noticed did not have a high level of accessibility. We've created this smaller version as a concept highlighting accessibility for screenreaders and keyboard navigation of the website, hoping to provide the same critical information about COVID-19, using the State of Colorado's own data source, to a wider audience of residents. 

If you'd like to contribute or learn more, you can find the project on GitHub (link:https://github.com/codefordenver/cdphe-accessible-covid19).

**Comment by joel-oe-lacey** [comment]
Added with the latest PR! (currently live) I added the blurb exactly as you have it, but if we want to modify in any way, let me know. Otherwise we can probably close this if it fits what you had in mind @anotherpatrickcollins.

**Comment by anotherpatrickcollins** [comment]
Looks good!
